### ISSUE TITLE
Disable "See More Tweets" or at least make it better

### ISSUE THREAD

**Issue by arturo182** [Bl4Cc4t/GoodTwitter2#112]
If you keep your tab open too long without checking latest tweets, twitter will start collapsing them into a hidden collection with a button "See More Tweets". Problem is that when you press it, twitter loads them but the scroll doesn't move so now you have to scroll down and remember what was the last tweet you saw. Terrible UX. I'd love it if it was possible to disable this "feature" or at least have the page scroll to the last tweet before these new tweets were loaded so you can just scroll up and read them.

**Comment by Bl4Cc4t** [comment]
Are you talking about legacy?
If not, then you probably have disableautoRefresh enabled, I have to improve that.
Scrolling down is a good feature to add to that

**Comment by arturo182** [comment]
I mean this (screenshot from google):
![](https://pbs.twimg.com/media/DZiGLOlVQAMXB3P.jpg)

Yes this is from the mobile app but it also happens on the website.

Not sure what you mean with legacy.

I have tried disableAutoRefresh but it was buggy (as you mentioned, so not complaining) so I turned it off.
But if you could have an option to enable scrolling to last tweet when you use disableAutoRefresh and click "Show x new tweets" that would be awesome (probably should only happen if the new tweets don't fit in the viewport, so if it's 1-2 new tweets and you see both when you click, no need to scroll). 

Sorry about all the complaining, I love your script even without these functions, it makes the new Twitter usable again :)

**Comment by Bl4Cc4t** [comment]
Oh, you mean that button... I didn’t even knew this existed on the desktop version.
I imagine this a bit harder to fix since it does not appear that often, this could probably take a while

**Comment by arturo182** [comment]
Not sure if helpful:
![image](https://user-images.githubusercontent.com/249082/84630847-cba00c00-aeec-11ea-8dcf-95171cea8c2c.png)

**Comment by Bl4Cc4t** [comment]
Going through some older issues sure makes me feel bad. You did need to open an issue twice to have it implemented to some extend :/

Does this scrolling thing still bother you? I'm not sure if this can be done in any good way, since the hidden tweets can range up from a few to a few thousand (depending on how many people you're following and the amount of time that has passed).

It would be cool to have an additional timeline open up when clicking this button or something similar instead of showing all the new tweets in place. But that probably will never happen...

I'll close this issue if it's okay for you.

**Comment by arturo182** [comment]
Oh wow, I didn't even realize I already had an issue for this, sorry.
It is still quite annoying, but I haven't tested the solution on non-stable yet, I see you're doing 0.0.30 soon so I'll check it out then.
