### ISSUE TITLE
Can't get all the content when using copy paste 

### ISSUE THREAD

**Issue by silicium2020** [Bl4Cc4t/GoodTwitter2#163]
**Please check the following before you continue**
- [ ] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [ ] Checked if the issue has not been reported before

**Describe the bug**
When i use twitter, i used to follow some master of science and try to collect what they say and learn them myself. So i copy their twits and saved them in the Microsoft word. 

When i use the 0.0.23 version extension, for example when i open someone's twits for the last 6 month, after using copy and paste function, i can get only very small part of the contect that i copied in the word 2016, . The majority of the content in the page can't be copied. 

So there is probably something wrong here, can you check it out ? 

Thank you very much !

**Screenshots**
For display issues, adding screenshots or even videos of your screen is recommended.

**Your configuation**
 - Browser (Chrome 83.0.4103.116)
 - Userscript Manager (Tampermonkey v4.10)

**Comment by Bl4Cc4t** [comment]
That happens because Twitter removes content that is not visible to the user when scrolling.
That is done to load the pages smoother, but on the other hand makes it hard for others to interact with the elements in some way (e.g. copying the contents of the tweets in your case).

I suggest you go check out another twitter project focused on retrieving tweets: [twint](https://github.com/twintproject/twint)
I think this suits yout needs more than a script focused on the pure looks of twitter (this project).

**Comment by silicium2020** [comment]
Thanks for replying. 

In fact, i just use the following address to visit twitter to show all the tweets that someone posted. 

https://twitter.com/search?f=tweets&vertical=default&q=from%3A(user id)&src=typd

and it works perfectly. 

I can get all the tweets on my screen with your script

just can't copy them. 

With your suggestion, you mean the problem that i met is not a layout problem. I am surprising cause when i use old extension goodtwists i can copy all the elements after changing the layout. 

Thanks for giving me the right advise. 

Have a good day

**Comment by Bl4Cc4t** [comment]
Okay, so I guess I can close this? :D

**Comment by silicium2020** [comment]
sure, go ahead, your call you are the boss ~~
