### ISSUE TITLE
Screwed up layout after reinstalling script

### ISSUE THREAD

**Issue by YoshiFan501** [Bl4Cc4t/GoodTwitter2#169]
The script was working fine, but I installed it on my new PC, and the layout is completely messed up. I reinstalled it on my old laptop to make sure that wasn't the problem, but it happened there too. Both are running Chrome 84 with Tapermonkey 4.10
![Twitter layout](https://user-images.githubusercontent.com/1903751/88247531-afb62580-cc63-11ea-92fb-77b0a395b9e6.png)

Here's what the goodtwitter settings look like for example

**Comment by AndrewPSSP** [comment]
The same has happened to me, when I changed the display language.
Changing the language back doesn't bring it back
![image](https://user-images.githubusercontent.com/68681298/88285809-a1115200-cce7-11ea-9542-f6974fa18bd5.png)

**Comment by Bl4Cc4t** [comment]
They changed the location of a resource the script loaded, causing the script to break.
I have removed everything related to that resource in https://github.com/Bl4Cc4t/GoodTwitter2/commit/1770fef191b7e6a9c6e94c330b82afcf55919973, so this issue should be fixed with the next version (will probably be released tomorrow).
