### ISSUE TITLE
Searching Followers/Following 

### ISSUE THREAD

**Issue by rockets1201** [Bl4Cc4t/GoodTwitter2#190]
In the old Twitter layout you could scroll all the way down on your or anyone elses followers/following and then search the entire lists. But now the way it refreshes when you scroll down it won’t let you. Only allows a portion. Like you see the first follower listed and do three "page downs" (PgDn key) and try to search, it won't find it. I hope you understand.

Thank you for all your hard work!

**Comment by rockets1201** [comment]
Is this even possible? It is impossible to search entire your or anyone elses followers/following.

**Comment by rockets1201** [comment]
Is this even possible at all? It is impossible to search your or anyone elses entire followers/following list.

**Comment by Bl4Cc4t** [comment]
Sorry I never answered you.

I theory, it should be possible to force any timeline to keep its content while off screen (the following page is a timeline too). This is essentially the same concept as the disableAutoRefresh option for the tweet timeline on `/home`. Unfortunately, I have problems implementing this and I don't really know how to do it better (it's currently pretty broken). If this gets fixed one day, this should work on these pages too.

Another option would be to make an entire new search for these pages with API calls.
Sadly there is no straight way to search for one user, that means it would require me to implement several API calls to build the index of one profile. Since you can only request 20 users per call, such a task can easily stack up to thousands of requests which is pretty much not feasible. I'm sure you would get temporarily disabled for so many requests.

Also, I'm sure you don't mean to do any harm by this, but I could also see this feature being abused in some way or another. There is probably a reason no working site exists which implements this feature, but this is only a guess.

So unless twitter introduces a new API point to search for one user (which I honestly doubt will ever happen), I probably will not implement this way of searching.
