### ISSUE TITLE
Legacy profiles remain disabled even by setting the legacy profile parameter true

### ISSUE THREAD

**Issue by hyredash** [Bl4Cc4t/GoodTwitter2#211]
I just downloaded GoodTwitter2, and enabled legacy profiles by editing the parameter, but the profiles remain the same. Any help?
![image](https://user-images.githubusercontent.com/73332734/96969675-02c5a000-1513-11eb-8d97-c52d64818ea7.png)

**Comment by zetorplugger** [comment]
@hyredash  how come you have that trend box on the left and you have a list of trends instead of What's happening?

did you change anything in the code to get the tend list and on the left? 

this is what I see 
![screenshot](https://user-images.githubusercontent.com/66390092/96998551-ebe37580-1533-11eb-9c35-9500e89d6a73.JPG)

**Comment by Bl4Cc4t** [comment]
@hyredash what "parameters" did you edit? Have you perhaps edited the source code?
Please don't do that. To change a setting of this script, simply navigate to the twitter settings (dropdown menu on the top right of the navbar) and go to the "GoodTwitter 2" section.

**Comment by Bl4Cc4t** [comment]
I'll close this since I heard nothing back. Feel free to reply again if the issue still exists.
