### ISSUE TITLE
Twitter profile pg banners are gone

### ISSUE THREAD

**Issue by Handmedown222** [Bl4Cc4t/GoodTwitter2#226]
Started yesterday, any twitter profile page I go to, including my own, are missing the banner and upper portion of the page. 
![image](https://user-images.githubusercontent.com/68014036/101166367-c602c380-35fd-11eb-85d5-5dd0777168d2.png)
If I turn off the Good Twitter app and go back to the current twitter layout, the pages will be complete again. I am using Microsoft Edge browser after my Chrome browser also quit working with the Good Twitter app giving me constant popups while on Twitter that it would no longer work with that browser.

**Comment by Bl4Cc4t** [comment]
They made a change in the display of the actual follower/following numbers, you can see that they now appear differntly when you hover over the numbers (without LPL enabled)

**Comment by Handmedown222** [comment]
Ok, you're talking to a computer greenie here. I see my bug reporting post is labelled #226 and your first comment says "fixes #226", but is there something I am suppose to do to get the fix? I have opened the menu for Tamper Monkey and clicked on "check for user script updates" but it says none are found. I have refreshed the twitter page. 
I clicked on your first comment and it took me to a page filled with lines of computer scripts but I don't know what to do, if anything while on that page. What is LPL? 
Thanks for trying to help me.

**Comment by Bl4Cc4t** [comment]
> Ok, you're talking to a computer greenie here. I see my bug reporting post is labelled #226 and your first comment says "fixes #226", but is there something I am suppose to do to get the fix? I have opened the menu for Tamper Monkey and clicked on "check for user script updates" but it says none are found. I have refreshed the twitter page.

Updating is generally a good idea. But since I haven't released the update when you posted your comment, there was not really a point in doing so.

> I clicked on your first comment and it took me to a page filled with lines of computer scripts but I don't know what to do, if anything while on that page.

What you clicked on is a commit – you can see it as an overview of what has been changed at one point. 

Git projects usually have two or more branches (like from a tree), where code is a different stages.
There is the `master` branch, which has the production ready code.
All the other branches are usually for internal development and not intended for public use, since they are mostly not stable/need improvements.

If you see that an issue has been labelled as ["fixed in dev branch"](https://github.com/Bl4Cc4t/GoodTwitter2/issues?q=is%3Aissue+is%3Aopen+label%3A%22fixed+in+dev+branch%22) or you only see that a commit says it should be fixed (like here, where I forgot to label it), that means that the issue is indeed fixed but only in the development branch.

With each new release, the fixes in the `dev` branch are merged into `master` and the update gets available to the end user.

---

I released the new version 20 min ago, so you should be able to update now.

**Comment by Handmedown222** [comment]
Thank you very much. I need to not be so impatient.

**Comment by Handmedown222** [comment]
Just updated and it worked! Problem solved.
