### ISSUE TITLE
High Contrast Breaks Lights Out Mode

### ISSUE THREAD

**Issue by clausies** [Bl4Cc4t/GoodTwitter2#248]
**Please check the following before you continue**
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
Hi! Me again, I found a small bug where changing the contrast while in lights out mode reverts the site back to the white background. It works with both the default and dim settings, and only triggers when you select **both** high contrast mode and lights out. I did try refreshing the page since sometimes colours do not work as indicated by the FAQ but given this is isolated to the lights out setting I believe it's probably something up with that code specifically.
It's not too big an issue but it is an accessibility setting it may be worth it to look into it!
Once again thank you for your work on this Userscript and stuff, it truly rocks. 👍

**Screenshots**
![screenshot1](https://user-images.githubusercontent.com/50381214/104563984-5c240380-5618-11eb-97a8-7ff59913c088.png)
![screenshot2](https://user-images.githubusercontent.com/50381214/104563992-5fb78a80-5618-11eb-94e0-caf37056d08a.png)

**Your configuration**
- Chrome 87.0.4280.141
- Tampermonkey v4.11
- Windows 10 Home)

**Comment by Bl4Cc4t** [comment]
Thanks for the report. I indeed didn't even know this setting existed...
For some reason the background color changes too when you use HC with the lights out theme... this broke the color scheme detection.

I now added support for the HC versions of the background colors since they do differ most of the time from the normal versions. I also updated the user color detection, so these should work better too.

> Once again thank you for your work on this Userscript and stuff, it truly rocks. 👍

Thank you for your kind works!
