### ISSUE TITLE
Not working as of today

### ISSUE THREAD

**Issue by bighairydaddy** [Bl4Cc4t/GoodTwitter2#249]
As of today, a few hours ago it stopped working, maybe twitter changed something that broke the entire script ? Maybe it will fix itself in a few hours, but right now the script doesnt work at all, its back to the default official twitter layout. Checked in settings in twitter to see if the GoodTwitter2 options are there at least, nope, gone completely.

Tampermonkey v4.11
GoodTwitter 0.0.28
![image](https://user-images.githubusercontent.com/34811552/104813269-cacbb180-5810-11eb-8e1a-ac4e5fbcbf57.png)

**Comment by Bl4Cc4t** [comment]
What browser are you using? Please don't delete the template if you file a bug, that defeats the purpose of having it in the first place.

I have no issues on Chrome and Firefox on the latest versions. Do you get any error messages in the console (F12)? If yes, please make screenshots of them.

**Comment by bighairydaddy** [comment]
sorry to bother you, its just.. back to normal on its own after a day

**Comment by Bl4Cc4t** [comment]
> sorry to bother you

Please don't say that, this page exists for the small amount of people (like you) that help me keeping this script stable!
Every report helps. I don't know what caused the issues since I had none, but I know Twitter sometimes rolls out changes that are only applied in some regions of the world.
Be sure to report back if it should happen again! :)
