### ISSUE TITLE
More white buttons

### ISSUE THREAD

**Issue by MistressAshai** [Bl4Cc4t/GoodTwitter2#272]
Same issue from #266

On certain accounts, the entire button instead of just the border is white.
![rOcqkq](https://user-images.githubusercontent.com/8222603/112662983-8a427280-8e15-11eb-8b5f-1c154424d4a3.png)

The "Edit Profile" button wasn't fixed
![GemWdC](https://user-images.githubusercontent.com/8222603/112663296-e3aaa180-8e15-11eb-8a6a-00eacc329503.png)

**Comment by Bl4Cc4t** [comment]
Thanks for noticing these. Looks like I forgot the edit button...
I don't know why the follow buttons would be filled white sometimes. Twitter's design decisions are very weird and make not much sense to me.
Since I do not have the "Topics to follow" section, could you please test if they disappear or change in some way once you click follow?

<details>
<summary>Also, if you are using Tampermonkey, you can test the rules I just added by doing the following:</summary>

1. On [Twitter](https://twitter.com), click on the TM icon 
1. Click on the plus next to the script name to expand it.
1. Click on "Edit"
  ![image](https://user-images.githubusercontent.com/6740726/112702004-6f621380-8e92-11eb-9974-dc9301691459.png)
1. Click on the tab "Externals"
1. Under Resources, click on "Edit" for the `.css` file
  ![image](https://user-images.githubusercontent.com/6740726/112702112-be0fad80-8e92-11eb-996d-8fba5c1c62e3.png)
1. Open [this link](https://gist.githubusercontent.com/Bl4Cc4t/727ebc230fe1e37b28d703ae496a2641/raw/74350d046c2712f7c17bf1090f1e9268a9d7c70e/gt2-css-2021-03-27) and copy the contents of that page into the text field of the editor.
1. Press <kbd>Ctrl</kbd>+<kbd>S</kbd> to save the file
1. Check if the buttons look like they should
1. Once you're done, please click on the delete button next to the edit button from step 5. If you don't do that, any future updates to the script won't get applied for that file.
</details>

**Comment by MistressAshai** [comment]
When clicking follow on "Topics to Follow", it removes the white background.

![image](https://user-images.githubusercontent.com/8222603/112709186-4d599880-8e74-11eb-86c8-d579b34b1e2b.png)

After trying the new rules, everything seems to work as intended!
![image](https://user-images.githubusercontent.com/8222603/112709228-ab867b80-8e74-11eb-8bbf-343799b85ae6.png)

But it seems like clicking follow on "Who to follow", makes the background white until the mouse is no longer hovering the button.

![image](https://user-images.githubusercontent.com/8222603/112709237-c658f000-8e74-11eb-9921-665762e12d91.png)

**Comment by Bl4Cc4t** [comment]
Hm okay... 
To fix that, I need your help again. Can you please to the following:
1. Right click a follow button and choose "Inspect"
2. Navigate in the element tree to the button element, it should look similar to this:
  ![image](https://user-images.githubusercontent.com/6740726/112733111-48611b80-8f3e-11eb-82d4-d95e5fe780c3.png)
2. Make a screenshot of that, like I did above
3. Open the screenshot and put the window side by side with your browser
4. Click on the inspected button and stay with your mouse on it.
5. Compare the values in the classes sections, there should be an additional one now
6. Post the class name here.

I usually do not use these classes, since they are not really reliable to work with (they could change at any time), but for this occasion, there is sadly no other way to change the color as far as I know.

Thanks for helping me tackle this down, I cannot do it myself since I don't have this change yet. I noticed that Twitter changes are often rolled out with some delay depending where you live.

**Comment by MistressAshai** [comment]
Looks like the class name is "r-1gg85qh".

Here are the screenshots just in case I read it wrong.

Before
![image](https://user-images.githubusercontent.com/8222603/112868090-852d2f80-9070-11eb-8cee-27d1f717127e.png)

After
![image](https://user-images.githubusercontent.com/8222603/112868124-8bbba700-9070-11eb-97b4-c91fce2372f6.png)

**Comment by Bl4Cc4t** [comment]
Okay, to confirm it works, can you please try [changing the css again](https://gist.githubusercontent.com/Bl4Cc4t/edb29ed5de242a8842b0c5a52818a865/raw/45cdb2835919cf9aa74911944b58e3644a1309bf/gt2-css-2021-03-29)?

**Comment by MistressAshai** [comment]
This edit does get rid of the white, but also gets rid of the red border and background of the button when trying to unfollow.

**Comment by Bl4Cc4t** [comment]
Could you make a screenshot of that? And if possibly post, what class the button has that makes it red. It should be pretty high up in the list.
![image](https://user-images.githubusercontent.com/6740726/113347256-2e0bb100-9335-11eb-9c02-febaa4ba0a80.png)

**Comment by Bl4Cc4t** [comment]
I hope this works for all users that have these strange white suggestions since I can't even use the classes you provided on my end.

**Comment by MistressAshai** [comment]
Seems like it IS "r-1ucxkr8", like in your screenshot, that makes the background color red, but the css you had me test overwrites it.

![image](https://user-images.githubusercontent.com/8222603/113467399-a2a72400-93f7-11eb-86ce-31e15ccfcc77.png)
![image](https://user-images.githubusercontent.com/8222603/113467405-a63aab00-93f7-11eb-980b-57588b9a96e3.png)

**Comment by Bl4Cc4t** [comment]
Oh, that only happens to the topics to follow buttons...? I didn't know that. [I hope this one works now](https://gist.github.com/Bl4Cc4t/4e794f9b3ad096e36713e508582a6e13/raw/398d6e7f59f9ad787d54819da56dc81605a1560e/gt2-css-2021-04-03) :D

**Comment by Bl4Cc4t** [comment]
Any update? @MistressAshai

**Comment by MistressAshai** [comment]
Oh, sorry! Yeah it seems to work now!

![image](https://user-images.githubusercontent.com/8222603/114847590-b4db7780-9d92-11eb-9d6c-30f12a5fcbbd.png)

**Comment by Bl4Cc4t** [comment]
okay, nice

**Comment by Bl4Cc4t** [comment]
Twitter seems to have added the colors back in.
So, everything can be deleted again :/
