### ISSUE TITLE
Weird Search Bar Glitch(?)

### ISSUE THREAD

**Issue by Setsugekka81** [Bl4Cc4t/GoodTwitter2#297]
So for the longest time everything has worked pretty well but this morning I load up twitter and there's some odd behavior where my username is in the search bar and when you click on it chrome has a dropdown like it's supposed to be a login box as my passwords and usernames for Twitter are all listed

![image](https://user-images.githubusercontent.com/84105670/118050306-00128700-b34d-11eb-9b0c-937213a00a7d.png)

Using violentmonkey and chrome ver  90.0.4430.212

**Comment by Bl4Cc4t** [comment]
Hm, I'm not sure how this could happen. Chrome should know when you're logged into Twitter, so it doesn't prompt you to login at the website all the time...
You can try to log out and then in again, I suspect this could fix the issue.

There's not much I can do about it though, since password managers usually pick the first input field they can find.
And changes on sites made by the browser are probably out of reach for userscripts to handle (or even extensions I think).

**Comment by Setsugekka81** [comment]
Turns out it's actually a Chrome glitch as poking around the internet seems to bring up it's not even just twitter it's happening with. Something to do with the autofill for payment methods and saved addresses or something so disregard this I guess lol.

**Comment by Bl4Cc4t** [comment]
Oh okay. Thanks for the update :D
