### ISSUE TITLE
translation button 

### ISSUE THREAD

**Issue by dropsim** [Bl4Cc4t/GoodTwitter2#32]
would you please try to bring back the translate button on TL/search, without clicking on the tweet it self?
the new layout does not support this function unfortunately..
best regard

**Comment by lread31** [comment]
It's missing from replies as well

**Comment by Bl4Cc4t** [comment]
I looked into it and found out that you need to be authorized to get a translation of a tweet.

Would you be comfortable with looking for your own token and adding it in the GT2 settings in order to have tweets translated? 

I cannot get the current users token by intercepting requests (which would be pretty dumb anyways since that would create huge security hole)
