### ISSUE TITLE
Potential fix for square profile pictures

### ISSUE THREAD

**Issue by Diyamund** [Bl4Cc4t/GoodTwitter2#331]
**Please check the following before you continue**
- [*] Checked if the feature has not been requested before

**Describe the feature**
I think I may have found a fix for square profile pictures.
```css
.r-sdzlij {
	border-radius: 9999px;
}
```
You see this CSS? This is for a <div> inside the element that was originally used for square profile pictures.
By appending the selector here onto every selector for the original profile picture CSS (I'm too lazy to do that) we could (maybe?) get square profile pictures working again

**Comment by Bl4Cc4t** [comment]
Thank you, but I tend to avoid these react selectors since they are not really reliable.
They are generated by the framework twitter uses and could change at any given moment.

By now I have implemented a fix for this issue in https://github.com/Bl4Cc4t/GoodTwitter2/commit/1366d3716303a69883dc31043faaa1ae59758274.

related: #322
