### ISSUE TITLE
Can't get rid of t.co redirect

### ISSUE THREAD

**Issue by Mavoy** [Bl4Cc4t/GoodTwitter2#349]
I was bothered with t.co redirect today, and I started to wonder if there's a setting in GT2 for that. There is, but it's not working for me. No matter if I have "expand redirects" checked or not, I still see links starting with "https://t.co", which is terrible for quick sharing (I'm specifically thinking, for extensions like Instapaper or AddToAny). I have to open the website in a new tab every time. Is there any way to fix it? I don't even think there's a working extension/userscript for that (and I've tried a few)

Chrome 93. Tampermonkey 4.13

Once again thank you for this great extension!

**Comment by Bl4Cc4t** [comment]
Hey, I fixed this a week ago in https://github.com/Bl4Cc4t/GoodTwitter2/commit/83dd9c1aac40488bda74b31bb049bb57f93fc255

Sorry for all the delays on the fixes...
I plan on doing more later this week, maybe I get around to releasing a new version then which incorporates this fix.

**Comment by Mavoy** [comment]
Ah sorry, I didn't find it in search. Thanks!

**Comment by spodermenpls** [comment]
> I don't even think there's a working extension/userscript for that (and I've tried a few)

@Mavoy Your choice in Chrome is unfortunate in this case, since the only "holistically" functioning and continuously maintained (Twitter's frequent changes in the background require equally frequent modifications) extension "Twitter Link Deobfuscator" (https://addons.mozilla.org/de/firefox/addon/twitter-link-deobfuscator/) only works with Firefox - probably due to missing APIs inside of Chrome.

@Bl4Cc4t I've seen your struggle with the implementation of this kind of feature for a while now, you may want to take a peak at TLD's source code at https://github.com/theAlinP/twitter-link-deobfuscator, it's able to uncloak all frequently used locations with "t.co"-ed links, it took however a lot of finesse and trial-and-error to accomplish it, I don't know if these kinds of processes can even be realized through a userscript.

**Comment by Bl4Cc4t** [comment]
@spodermenpls I'm sorry, I don't really know what you're talking about. Expanding the t.co links was never a problem.
The reason it broke this time was that a CSS selector didn't work anymore because some elements got rearranged in the DOM.

The only stuggle I had was the missing time for this project, that's the reason everything takes/took so long to fix.
Now that I have a bit more again, I should be able to repair quite a bit.

**Comment by spodermenpls** [comment]
@Bl4Cc4t I am sorry, I jumped the gun on assuming that GT2 is only capable of uncloaking simple text links, not Twitter Cards (I think you call them "embedded") and others. since this was the behaviour I experienced when I tested it out some months ago (without the accomodations you've made now). When faced with uncloaking Cards, the dev of Twitter Link Deobfuscator went the route of intercepting the JSON packages send by Twitter and swapping them out before reinjecting them, your script therefore shows that this isn't by all means necessary, good work on your part. At least 2 "holistically" working t.co-uncloakers, then. 😀 (even though, GT2 doesn't seem to be able to uncloak links inside the DM drawer and the DM page, at least yet?)

I noticed however that there is a noticeable delay of some odd seconds (when using GT2's uncloaking) before the actual link is being displayed instead of the t.co one, (probably first and foremost due to the userscript manager acting as a relay), so I guess TLD still has a competitive advantage in that department. 😅

On a side note, when I tried to install the latest Dev build, my Violentmonkey couldn't load the "emoji-regex.txt" depedency and aborted the installation. Is this an VM-specific issue, or will there be changes to the release build that circumvent this error?

**Comment by Bl4Cc4t** [comment]
You didn't need to delete your original comment...
> I am sorry, I jumped the gun on assuming that GT2 is only capable of uncloaking simple text links, not Twitter Cards (I think you call them "embedded") and others. since this was the behaviour I experienced when I tested it out some months ago (without the accomodations you've made now).

Cards should work since v0.30, I added support for that in https://github.com/Bl4Cc4t/GoodTwitter2/commit/6ed7004bb8c91af2d4483786ae2992524862e732 I think.

> When faced with uncloaking Cards, the dev of Twitter Link Deobfuscator went the route of intercepting the JSON packages send by Twitter and swapping them out before reinjecting them, your script therefore shows that this isn't by all means necessary, good work on your part. 

Intercepting network requests is something I'd like to avoid, I don't even know if you can do that in a userscript really.
This script works like this: it waits for the user hovering over a tweet and then sends a request for that tweet via the twitter api. It then replaces the shortened url with the original/"expanded" url.

> At least 2 "holistically" working t.co-uncloakers, then. 😀 (even though, GT2 doesn't seem to be able to uncloak links inside the DM drawer and the DM page, at least yet?)

I don't use that feature that often on desktop, so I didn't even knew the links there were also shortened... That really sucks.
I'm not sure how to accomplish that at the moment, but I opened a new issue here: https://github.com/Bl4Cc4t/GoodTwitter2/issues/351
This won't be added for the next release though, you may have use that other extension for this purpose.

> I noticed however that there is a noticeable delay of some odd seconds (when using GT2's uncloaking) before the actual link is being displayed instead of the t.co one, (probably first and foremost due to the userscript manager acting as a relay), so I guess TLD still has a competitive advantage in that department. 😅

An extension will always be faster than a userscript sadly, that's true. Also, intercepting a network request eliminates having the t.co link there in the first place, so you don't even see it happening.

> On a side note, when I tried to install the latest Dev build (to test the t.co-uncloaking capabilities), my Violentmonkey couldn't load the "emoji-regex.txt" dependency and aborted the installation. Is this a VM-specific issue, or will there be changes to the release build that circumvent this error? - Addendum: I just checked it with the latest Violentmonkey beta, the emoji-txt file causes the same error there too.

It cannot load that file because it does not exist yet with the url it has in the script. It's only in the dev branch, so you need to change the url accordingly (replace `master` with `dev`)

**Comment by spodermenpls** [comment]
> You didn't need to delete your original comment...

Both sections of my post were made under false pretences, away with it.

>This script works like this: it waits for the user hovering over a tweet and then sends a request for that tweet via the twitter api. It then replaces the shortened url with the original/"expanded" url.

That's good to know, it's more like a "semi-automatic" mechanism then, instead of "no interaction needed", like with TLD.

> I don't use that feature that often on desktop, so I didn't even knew the links there were also shortened... That really sucks.
> This won't be added for the next release though, you may have use that other extension for this purpose.

All links get t.co'ed  - and thereby spiked with a count pixel (<- 99% sure about that) - no matter where. 😅 I will always stay with TLD (since I spent so many hours in tandem with the dev beta-testing/debugging it and getting it to the fine state it is in now), however adding it would probably benefit a lot of GT2 users, that don't use Firefox and/or don't want a dedicated extension for that job.

> An extension will always be faster than a userscript sadly, that's true. Also, intercepting a network request eliminates having the t.co link there in the first place, so you don't even see it happening.

When one is on the receiving end, yes, when one sends a Card or a link (especially inside the DMs), there still can be delay, though.

> It cannot load that file because it does not exist yet with the url it has in the script. It's only in the dev branch, so you need to change the url accordingly (replace master with dev)

Yes, I've figured that out later - also since the same thing happens with the release build now, because mathiasbynens changed the path for one file upstream. Never had a dependency not loading before, therefore didn't know immediately how to tackle it, but smooth sailing by now.
