### ISSUE TITLE
script doesn't work on firefox + suggestions

### ISSUE THREAD

**Issue by Aridow** [Bl4Cc4t/GoodTwitter2#4]
The script doesn't work on firefox for me. Well, it does for a few seconds then it disappears. 

Also, here are some suggestions that I think would be good :
- I think the "What's happening ?" part is too big compared to old layout
- I think it would be great if we could middle click on trends to open them in a new tab
- Is there a possibility to have the same photos layout than before ? example : https://i.imgur.com/XEJecWw.png
- Lastly, it looks like all news tweets in TL are loaded at the same time in the new layout, without the messages "x news tweets"

I know there is many suggestions and this script is made to be a hybrid, but there is so many details that make this new layout less ergonomic... so I understand if these suggestions are not possible. 

Thanks for your work !

**Comment by Bl4Cc4t** [comment]
> The script doesn't work on firefox for me. Well, it does for a few seconds then it disappears.

For me, it doesn’t show at all after installing, I have to hard reload (Shift+Ctrl+R).
I think I forgot to mention that in my reply, sorry.

If that doesn’t help, then I’m not really sure what the issue is.
I’m on a fresh Firefox v76.0.1 and everything works fine :)

---

As for your suggestions, I’ll see what can be done.

- [ ] "What's happening?" part is too big compared to old layout
- [ ] trends should be anchors again
- [ ] old photo layout ![](https://i.imgur.com/XEJecWw.png)
- [ ] option to disable auto refresh

**Comment by Bl4Cc4t** [comment]
I think the photo layout is a bit out of reach, but maybe someone else wants to add that feature.

**Comment by Aridow** [comment]
It seems the "What's happening" part became big again, for me (Firefox/Chrome).

**Comment by Bl4Cc4t** [comment]
Can you post a screenshot please?

**Comment by Aridow** [comment]
Sure, here is a screenshot on Chrome with the script : 
![image](https://user-images.githubusercontent.com/65539338/97090255-d35c8380-1637-11eb-8075-9d1ba648d439.png)

And without : 
![image](https://user-images.githubusercontent.com/65539338/97090047-c3dd3a80-1637-11eb-9db8-910b0db748a4.png)

**Comment by Bl4Cc4t** [comment]
Ah, you're talking about this section. I thought you meant the trends, since they are named "What's happening" for some people as well, that confused me.
You're right, I'll change that right away.

**Comment by Bl4Cc4t** [comment]
frick, I accidentally pushed this to the master branch.
Welp, enjoy the instant change I guess :c
