### ISSUE TITLE
Banner/Timeline Scroll [Legacy Profile]

### ISSUE THREAD

**Issue by NathanChappaFifteen** [Bl4Cc4t/GoodTwitter2#463]
Very sorry for the mess up, Anyway;
When I go to a profile with legacy layout on, the timeline, as well as the banner, seems to glitch whenever you scroll down and back up again. Do you think you can have the banner scroll down and up with the timeline instead of looking like it's getting crushed in the middle as shown in the video?
https://user-images.githubusercontent.com/111619173/185845434-9193cb90-d592-480d-8743-698687c39b5f.mp4

**Comment by Bl4Cc4t** [comment]
The banner having a parallax effect (as you said "getting crushed in the middle" :D) is intended behavior. The original layout had that as well.

As for the free space appearing under the profile: that only happens when you resize your viewport in any way (e.g. resizing the window or opening the developer tools). This will however (hopefully) be fixed in the rewrite I'm currently doing!

**Comment by NathanChappaFifteen** [comment]
Alright, thanks. 👍
