### ISSUE TITLE
Option to disable views counter?

### ISSUE THREAD

**Issue by dankxen0n** [Bl4Cc4t/GoodTwitter2#510]
this new feature twitter just added is probably gonna make my (and other people using this's) anxiety skyrocket so itd be nice to have a feature to get ridda it if at all possible

**Comment by TechoGit** [comment]
https://gist.github.com/wukko/5c34f690986fc0e85b2f1aeaacc08d7c 

could be add to this since its just css related, if you use ublock or anything like that you can import that into the "My filters"  sections" 

hope this is useful

**Comment by geyerbri** [comment]
I don't know if you're interested in extending this enhancement further, but the views counts are presented in a different way on individual tweets, rather than the way on the timeline or as replies:

![image](https://user-images.githubusercontent.com/5496867/212445662-7b39fba0-0c08-4045-99d1-f2ba99af3b49.png)

I would imagine blocking the analytics for this spot would be just as easy?

**Comment by Bl4Cc4t** [comment]
argh, missed that one :)
thanks for the heads up!

**Comment by Bl4Cc4t** [comment]
Looks like I accidentally added a race condition... 
Thank you so much for actually testing what I put out, it's really appreciated!
