### ISSUE TITLE
About the scrollbar issue

### ISSUE THREAD

**Issue by Aridow** [Bl4Cc4t/GoodTwitter2#57]
It seems to be an issue I only have on Firefox when "sticky sidebars" is disabled : in some random pages,  for example https://twitter.com/TwitterSupport/with_replies, when I scroll, the scrollbar is behaving strangely, jumping up and down. If it helps, I tried to delete the sidebars with uBlock Origin and it fixed it. 
I currently use the last update of Good Twitter 2 and the last Firefox 77.0.

**Comment by Aridow** [comment]
I don't have "Bigger Image Previews" enabled. I tried to enable it but I can't reproduce the issue without "Sticky Sidebars" disabled. Here what I have enabled :  
![Capture](https://user-images.githubusercontent.com/65539338/83672520-aea73700-a5d6-11ea-9c22-1cd77c2b916d.PNG)

And here is a video of the scrollbar with these settings : 
https://gyazo.com/d6cf98b789512de604bc339bd6b2859b

**Comment by Bl4Cc4t** [comment]
> Edit : Don't know if it's related, but when I don't scroll and tweets load, sometimes the screen doesn't stay focused on the tweet I am reading.

That should be caused by biggerImagePreviews or disableAutoRefresh (not sure).

about this issue: found it.
this here is what’s causing the poor scrollbar to behave like this (notice the values of -2 million):
![image](https://user-images.githubusercontent.com/6740726/83949610-25d20a80-a825-11ea-9d7b-5dc4340b011f.png)

and here is how it should look:
![image](https://user-images.githubusercontent.com/6740726/83949614-279bce00-a825-11ea-9837-1b80c84bb517.png)
