### ISSUE TITLE
Change Color Settings

### ISSUE THREAD

**Issue by CJ040506** [Bl4Cc4t/GoodTwitter2#58]
It would be cool if we could change the color settings like on the legacy twitter. I really like to use muted colors, or dark shades of colors, because it's easier on the eyes. The twitter blue and all the other new twitter color options are way too flashy for my taste. On top of that, goodtwitter2 seems to force some elements in twitter-blue even if I picked another color.

Could you maybe implement the option to pick a color for all things twitter displays in color (twitter-blue or user chosen color)
I used to have different colors for multiple accounts, but at this point I'd be fine if I could give them all the same muted color to start with.

**Comment by Bl4Cc4t** [comment]
Okay, so you essentially want the 5 other colors back?
![image](https://user-images.githubusercontent.com/6740726/83672262-42c4ce80-a5d6-11ea-9c43-3855e3b87f4d.png)

> On top of that, goodtwitter2 seems to force some elements in twitter-blue even if I picked another color.

This thing always gets pointed out. It is the only thing listed in the readme under [hints](https://github.com/Bl4Cc4t/GoodTwitter2#hints)

> I used to have different colors for multiple accounts, but at this point I'd be fine if I could give them all the same muted color to start with.

Multiple accounts with different colors, this is something I have not thought about yet. I will add that for sure.

**Comment by Mel47** [comment]
Hope it's ok to jump in here...just wanted to add that the color choices we used to be able to pick were quite numerous - it's been a really long time since I set my colors, but it was a hexadecimal RGB color values swatch chart that you could choose from. If I recall, I think you could even type in the hexadecimal value number to get the color you want too. Not sure how easy it'd be to add something like that though. I had a nice muted dark blue/purple color as I too prefer the more muted color choices, and it matched my profile banner pic. (being a digital artist I'm picky about colors ;) ).

**Comment by nipapi14** [comment]
yeah the hex colors allowed for way more customization than 6 colors only; become clones y'all

i want custom colors back too. literally the only thing and then goodtwitter2 would be great

**Comment by CJ040506** [comment]
> Okay, so you essentially want the 5 other colors back?

No, like the others I'm specifically requesting a hex color input. I like colors such as 660000 555555 and 556644. The pre-chosen color options are all too bright and flashy for me.

> image

I cannot even find that option. I only get the 5 new twitter colors and I don't like any of them.

> Multiple accounts with different colors, this is something I have not thought about yet. I will add that for sure.

I'm afraid that won't work, as the color options are now end-user based and no longer profile-based. It's a shame really. At least the profile accent colors should be profile-based so people can express themselves and match colors to profile-headers etc.
That's why I'm saying I'd be fine if I could at least pick a muted color (hex-style) for my view/all accounts.

**Comment by nipapi14** [comment]
it was in old twitter those colors. then they reduced it to 5 super bright defaults.

if you could at least change the user color to be anything like how the hex code system worked that'd be great, surely it couldn't be too hard

multiple user colors doesn't seem possible like cj said, at the very least get us out of this 6 color monotony

**Comment by Bl4Cc4t** [comment]
About a year later and I finally implemented this option. I'm sorry that it took so long...
![image](https://user-images.githubusercontent.com/6740726/119571871-30790d00-bdb2-11eb-9490-00e88c15177a.png)

However, it is a bit experimental since I'm using classes for this to work (there is no other way).
Why are classes bad? Because they are generated by the framework twitter uses (react) and could possibly change at any given time without warning.
