### ISSUE TITLE
Twitter search bar has disappeared

### ISSUE THREAD

**Issue by dandelion1974** [Bl4Cc4t/GoodTwitter2#93]
My search bar has disappeared this morning

**Comment by Bl4Cc4t** [comment]
on what page?

**Comment by arturo182** [comment]
If you are on the Home page, then click a trend the search bar is hidden because there is one in the middle, but then when you click back to Home, l the search bar in the top right is still hidden. This is on 0.0.20

**Comment by fid3lito** [comment]
That has been happening to me aswell, every now and then I have to refresh the page for it to come back

**Comment by arturo182** [comment]
Here's a preview
![twitter](https://user-images.githubusercontent.com/249082/83968408-5ff4e800-a8c9-11ea-86c0-cb74f3630fa9.gif)

**Comment by zetorplugger** [comment]
Yes, this has been a problem from the get go. Now a white line appears under the space where the search box is supposed to be, when you go to a trend and then back home


![white line](https://user-images.githubusercontent.com/66390092/83971364-58d6d580-a8db-11ea-9a14-73c7468374d0.png)

**Comment by BrandtnerKPW** [comment]
After searching using this bar, search bar also disappears.
With script from dev branch (0.0.21).

**Comment by Bl4Cc4t** [comment]
I thought it was a good idea to remove it on the search page since you already have a big search bar.
Also, the small one breaks (it does not respond anymore) when you search with it and land on `/search`.

Do we need two bars?

About the issue itself: I removed a bit too much code, I thought it was not needed anymore (don’t ask why, I’m stupid :D)
